# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: examples.config.kubernetes.io/v1alpha1
kind: ResourceSizer
metadata:
  annotations:
    config.kubernetes.io/local-config: "true"
    config.k8s.io/function: |-
      container:
        image: gcr.io/kustomize-functions/example-tshirt:v0.1.0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-gke
  labels:
    app: hello
  annotations:
    tshirt-size: 'small' # {"$ref":"#/definitions/io.k8s.cli.setters.tshirt-size"}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: helloworld-gke
        image: gcr.io/kpt-dev/helloworld-gke:0.1.0
        ports:
        - name: http
          containerPort: 80
        env:
        - name: PORT
          value: "80"
        resources:
          requests:
            cpu: 200m
            memory: 50MiB
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-gke
  labels:
    app: hello
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
  - protocol: TCP
    port: 80
    targetPort: http
