apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PROJECT_ID-yourspace # {"$kpt-set":"proj-namespace"}
  name: wordpress
spec:
  replicas: 5
  template:
    spec:
      containers:
      - name: wordpress
        image: wordpress:1.8.1
