# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Go
on:
  # Trigger the workflow on push or pull request,
  # but only for the 'next' branch
  push:
    branches:
      - next
  pull_request:
    branches:
      - next
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Build, Test, Lint
      run: |
        git config --global user.email you@example.com
        git config --global user.name Your Name
        make all
        make test-docker
    - name: "Upload Linux Binary"
      uses: actions/upload-artifact@v2
      with:
        name: kpt-linux
        path: kpt-linux
        retention-days: 1
    - name: "Upload Darwin (MacOS) Binary"
      uses: actions/upload-artifact@v2
      with:
        name: kpt-darwin
        path: kpt-darwin
        retention-days: 1
    # - name: "Upload Windows Binary"
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: kpt-windows.exe
    #     path: kpt-windows.exe
    #     retention-days: 1
  
  validate-binaries:
    name: "Validate Binaries"
    needs: "build"
    runs-on: ${{ matrix.os }}
    strategy:
      # Do not fail fast for validation. This gives us signals for all OS's.
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            binary: kpt-linux
          - os: macos-latest
            binary: kpt-darwin
          # Uncomment to enable Windows testing
          # - os: windows-latest
          #   binary: kpt-windows.exe
    steps:
      - name: Download Binary
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.binary }}
          path: "kpt"
      # For linux builds allow execution of kpt
      - name: Update permissions
        if: matrix.os != 'windows-latest'
        run: chmod +x ./kpt/*
      - run: "./kpt/${{ matrix.binary }} version"
